# Generated by Django 4.1.2 on 2022-10-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='count',
        ),
    ]
